### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/commons/compress/PasswordRequiredException

### ISSUE THREAD

**Issue by trevor** [michaelklishin/pantomime#15]
Using

  [me.raynes/fs "1.4.6"]
  [com.novemberain/pantomime "2.7.0"]

This returns correctly:

(pantomime.mime/mime-type-of (me.raynes.fs/file "/path/myfile"))
"application/x-tar"

However when using 2.8.0 an exception is thrown:

```
ClassNotFoundException org.apache.commons.compress.PasswordRequiredException  java.net.URLClassLoader.findClass (URLClassLoader.java:381)

java.lang.NoClassDefFoundError: org/apache/commons/compress/PasswordRequiredException
ZipContainerDetector.java:131 org.apache.tika.parser.pkg.ZipContainerDetector.detectArchiveFormat
ZipContainerDetector.java:87 org.apache.tika.parser.pkg.ZipContainerDetector.detect
CompositeDetector.java:77 org.apache.tika.detect.CompositeDetector.detect
         Tika.java:156 org.apache.tika.Tika.detect
         Tika.java:287 org.apache.tika.Tika.detect
           mime.clj:38 pantomime.mime/eval15432[fn]
           mime.clj:24 pantomime.mime/eval15411[fn]
```

**Comment by michaelklishin** [comment]
This is a dependency issue: a class isn't found. I don't think Pantomime can do anything about it. Possibly zip container detector has a dependency which is optional.

**Comment by trevor** [comment]
`mime-type-of` also fails on files that aren't zip files.


Here's a patch that fixes the issue:

```clj
:dependencies [[org.clojure/clojure "1.7.0"]                 
               [org.apache.tika/tika-parsers "1.9"]]
```

**Comment by michaelklishin** [comment]
@trevor alright, lets add `tika-parsers` dependency to Pantomime then. Please submit a PR?

**Comment by trevor** [comment]
@michaelklishin Sounds good, I'll look into it. Thanks!

**Comment by willspecht** [comment]
the bump to tika 1.14 seems to have recreated this issue.

**Comment by michaelklishin** [comment]
A quick search suggests that `PasswordRequiredException ` comes from Apache Commons.

**Comment by jeremybmerrill** [comment]
this may be redundant to say, but I've "fixed" the issue by adding a dep on `      [org.apache.commons/commons-compress "1.13"]` to my project.clj

**Comment by manikavasagam-vananservices** [comment]
I'm  getting a error -  java.lang.NoClassDefFoundError: org/apache/commons/compress/archivers/zip/ZipArchiveOutputStream

**Comment by michaelklishin** [comment]
All `java.lang.NoClassDefFoundError`s are not caused by this library. Tika has plenty of optional dependencies, if you are going to use some of them, make sure those artifacts are on the classpath.
