### ISSUE TITLE
Expose type inheritance feature

### ISSUE THREAD

**Issue by doriantaylor** [michaelklishin/pantomime#17]
I was looking for functionality similar to other shared-mime-info interfaces that will tell you if a type is a subtype of some other type, e.g. that `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` is an `application/zip`. This is exposed in [`org.apache.tika.mime.MediaTypeRegistry`](http://tika.apache.org/1.12/api/org/apache/tika/mime/MediaTypeRegistry.html).

I have already implemented a patch. If you're cool with PRs I can fork this project and do one. I have also included a protocol for coercing objects between `MimeType` and `MediaType`.

(Why does Tika have two separate, completely unrelated classes to represent type objects, anyway?)

**Comment by michaelklishin** [comment]
@doriantaylor please submit a PR. Thank you.

**Comment by doriantaylor** [comment]
Done; https://github.com/michaelklishin/pantomime/pull/21

**Comment by michaelklishin** [comment]
Let's keep the issue open until #21 is merged.

**Comment by doriantaylor** [comment]
oh, sure; fatfingered it over here.
