### ISSUE TITLE
setTimeout() ? 

### ISSUE THREAD

**Issue by joefromct** [michaelklishin/pantomime#18]
I've been trying to figure out if there is someway to set the timeout for the tesseract process.

I occasionally receive errors such as `org.apache.tika.exception.TikaException: TesseractOCRParser timeout`... i'm willing to be more patient then 1200 seconds if i can figure out where to increase this.

I'm thinking maybe this has something to do with the [ParseContext](https://github.com/michaelklishin/pantomime/blob/master/src/clojure/pantomime/extract.clj#L56) but haven't found exactly where/how. 

Any tips appreciated, thanks.

**Comment by michaelklishin** [comment]
I believe https://github.com/michaelklishin/pantomime/pull/19 indirectly addresses this.
