### ISSUE TITLE
Not parsing email attachments 

### ISSUE THREAD

**Issue by steven-cutting** [michaelklishin/pantomime#22]
Using `(extract/parse-extract-embedded "pg1661.eml")` does not parse the attachments from the test email that I am using. It leaves them as part of the `:text`, instead of parsing them and then providing them as temp files (with the paths provided by the `:embedded` key).

Here is the email that I'm testing with: [test_email.zip](https://github.com/michaelklishin/pantomime/files/353261/test_email.zip)
(It's in a zip because github won't allow me to upload a .eml file)

The email was originally produced using gmail, the files were produced using Libreoffice.
There are four different attachments to the email file. 1 - html, 1 - pdf, 1 - docx, 1 - zip

I'm going to continue to investigate this and I will post anything else that I uncover.

**Comment by michaelklishin** [comment]
This is something to report to/investigate with Tika developers. Pantomime itself doesn't implement any parsers.
