### ISSUE TITLE
Support latest Tika ?

### ISSUE THREAD

**Issue by turbopape** [michaelklishin/pantomime#23]
Hey,

Tika turned 1.14 in October 2016. Will it be simple to bump its dependency in pantomime ?

Cheers,

Rafik

**Comment by michaelklishin** [comment]
I don't know. Feel free to submit a pull request. It's trivial for individual applications to override the Tika version used, too, using Leiningen/Maven dependency exclusions.

**Comment by willspecht** [comment]
bump to 1.14 seems to cause the issue described here, https://github.com/michaelklishin/pantomime/issues/15

Is anyone else seeing this?

**Comment by michaelklishin** [comment]
A quick search suggests that `PasswordRequiredException ` comes from Apache Commons. I don't see anything in `tika-parsers` or `tika-core` directly depending on it but a lot of Apache code does.
So this may be a missing dependency for `tika-parsers` but I cannot reproduce it.
