### ISSUE TITLE
2.10.0 (or 2.9.0) on clojars?

### ISSUE THREAD

**Issue by joefromct** [michaelklishin/pantomime#24]
Hi, 

Is there any reason 2.10.0 (or even 2.9.0) aren't on clojars? 

I want to try out the `make-confg` functionality, it'll be easier then messing about with the classpath and overriding things.  

Thanks, -Joe

**Comment by michaelklishin** [comment]
They were [never released?](https://github.com/michaelklishin/pantomime/releases)

Those who need to try development versions can install and use a snapshot locally quite trivially.
