### ISSUE TITLE
pantomime.web/mime-type-of won't detect json content

### ISSUE THREAD

**Issue by buzzdan** [michaelklishin/pantomime#26]
Hi, 
I'm trying to detect whether my request body is json or not but always get the wrong answer

here's what i try on the REPL:

```
(pantomime.web/mime-type-of "{\"name\":\"lala\"}" {"Content-Type" "application/json"})
=> "text/plain"
```

Am I missing anything ?

**Comment by alexott** [comment]
I think that underlying Tika library isn't able to detect it, so I suggest to try to reproduce error with Tika & fail error against it...

P.S. effective detection of JSON is quite hard, if you don't want to consume resources by parsing it...
