### ISSUE TITLE
tika warning

### ISSUE THREAD

**Issue by r-custodio** [michaelklishin/pantomime#28]
I'm getting the following warning, is there anyway to suppress (or fix) them?

```
Jun 06, 2018 6:40:54 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: JBIG2ImageReader not loaded. jbig2 files will be ignored
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io for optional dependencies.
TIFFImageWriter not loaded. tiff files will not be processed
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io for optional dependencies.
J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io for optional dependencies. 

Jun 06, 2018 6:40:54 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: org.xerial's sqlite-jdbc is not loaded.
Please provide the jar on your classpath to parse sqlite files.
See tika-parsers/pom.xml for the correct version.  
```

**Comment by deg** [comment]
It looks like these warnings can be controlled by a Tika config file, but I'm not sure how to include that into my Clojure project.

I don't have time to chase this today, but here's what I found so far:
- https://issues.apache.org/jira/browse/TIKA-2490
- http://svn.apache.org/viewvc/jackrabbit/oak/trunk/oak-lucene/src/main/resources/org/apache/jackrabbit/oak/plugins/index/lucene/tika-config.xml?view=markup&pathrev=1820557
- https://tika.apache.org/1.18/configuring.html

**Comment by ivarref** [comment]
Hi. Here is a solution to this problem:

Create a file `resources/tika-config.xml` with the following content:

```
<properties>
    <service-loader initializableProblemHandler="ignore"/>
</properties>
```

In a namespace that is loaded *before* you require Pantomime, add the following code:

```clojure
(System/setProperty "tika.config" "tika-config.xml")
```

See the [tika documentation](https://tika.apache.org/1.9/configuring.html#Using_a_Tika_Configuration_XML_file) for other ways to set the config file.

CC @deg @r-custodio

**Comment by michaelklishin** [comment]
Thank you @ivarref. This project probably should not be in the business of shipping Tika config files.
