### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ivarref** [michaelklishin/pantomime#30]
Hi, and thanks for a fine library!

Is there any chance of a new release? I'd particularly be interested in using pantomime with #29.

Thanks and kind regards.

**Comment by michaelklishin** [comment]
Done.

**Comment by ivarref** [comment]
Thanks, that was quick!

**Comment by michaelklishin** [comment]
@KaliszAd wrong question. The right question to ask is "how can I help update this tiny library for the most recent version of Tika".

The answer is "just go ahead and do it". Asking others to do what *you* need is not how open source software works.
