### ISSUE TITLE
Question: Custom file parser in Clojure

### ISSUE THREAD

**Issue by joshkh** [michaelklishin/pantomime#32]
The Tika documentation recommends adding custom parsers by extending the AbstractParser Java class and then listing the new customer parser classes in the `tika-parsers/src/main/resources/META-INF/services/org.apache.tika.parser.Parser` file:

https://tika.apache.org/1.21/parser_guide.html#Create_your_Parser_class

Any tips for an idiomatic implementation with `pantomime`? Must custom parsers be compiled AOT and then loaded via `pantomime.extract/make-config`, or can they be written purely in Clojure and passed to Tika at runtime?

Thanks for the excellent library!

**Comment by michaelklishin** [comment]
This is a Tika question. The docs don't list a way to make a new parser available. Pantomime won't really care. "Please update this file" suggests that there is no way to register a parser at runtime.

However, [this doc guide](https://tika.apache.org/1.21/configuring.html) suggests that there is a way.

**Comment by joshkh** [comment]
Cheers, thanks @michaelklishin
